version: '3'
services:
        db:
                image: mysql:8.0.19
                restart: always
                environment:
                        - MYSQL_DATABASE=example
                        - MYSQL_ROOT_PASSWORD=pass
        web:
                build: .
                ports:
                     - "5000:5000"
        redis:
                image: "redis:alpine"
